"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_blocked_numbers_phone_number'), 'blocked_numbers', ['phone_number'], unique=False)
    
    op.create_table('command_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usage_count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_command_aliases_alias'), 'command_aliases', ['alias'], unique=False)
    
    op.create_table('spam_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hit_count', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Enum('GUEST', 'USER', 'PREMIUM', 'ADMIN', name='usertier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('command_count', sa.BigInteger(), nullable=False),
    sa.Column('daily_command_count', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    
    op.create_table('command_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_logs_command'), 'command_logs', ['command'], unique=False)
    op.create_index(op.f('ix_command_logs_created_at'), 'command_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_command_logs_user_id_created_at'), 'command_logs', ['user_id', 'created_at'], unique=False)
    
    op.create_table('game_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('state_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('moves', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_states_is_active'), 'game_states', ['is_active'], unique=False)
    op.create_index(op.f('ix_game_states_user_id_game_type'), 'game_states', ['user_id', 'game_type'], unique=False)
    
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_phone_number_window'), 'rate_limits', ['phone_number', 'window_start'], unique=False)
    op.create_index(op.f('ix_rate_limits_window_start'), 'rate_limits', ['window_start'], unique=False)
    
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_celery_task_id'), 'reminders', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_reminders_is_completed'), 'reminders', ['is_completed'], unique=False)
    op.create_index(op.f('ix_reminders_scheduled_at'), 'reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    
    # Insert default command aliases
    op.bulk_insert('command_aliases', [
        {'alias': 'w', 'command': 'weather', 'description': 'Shortcut for weather', 'usage_count': 0},
        {'alias': 'h', 'command': 'help', 'description': 'Shortcut for help', 'usage_count': 0},
        {'alias': 'j', 'command': 'joke', 'description': 'Shortcut for joke', 'usage_count': 0},
        {'alias': 'q', 'command': 'quote', 'description': 'Shortcut for quote', 'usage_count': 0},
        {'alias': 'n', 'command': 'news', 'description': 'Shortcut for news', 'usage_count': 0},
        {'alias': 'r', 'command': 'reminder', 'description': 'Shortcut for reminder', 'usage_count': 0},
        {'alias': 'calc', 'command': 'calculate', 'description': 'Shortcut for calculate', 'usage_count': 0},
        {'alias': 'math', 'command': 'calculate', 'description': 'Shortcut for calculate', 'usage_count': 0},
        {'alias': 'flip', 'command': 'coin', 'description': 'Shortcut for coin flip', 'usage_count': 0},
        {'alias': 'dice', 'command': 'roll', 'description': 'Shortcut for roll', 'usage_count': 0},
        {'alias': 'pass', 'command': 'password', 'description': 'Shortcut for password', 'usage_count': 0},
        {'alias': 'pwd', 'command': 'password', 'description': 'Shortcut for password', 'usage_count': 0},
        {'alias': 'tod', 'command': 'truthordare', 'description': 'Shortcut for truth or dare', 'usage_count': 0},
        {'alias': 'wyr', 'command': 'wouldyourather', 'description': 'Shortcut for would you rather', 'usage_count': 0},
    ])
    
    # Insert default spam patterns
    op.bulk_insert('spam_patterns', [
        {'pattern': r'\b(buy now|click here|limited time|act now)\b', 'pattern_type': 'regex', 'is_active': True, 'hit_count': 0, 'description': 'Common spam phrases'},
        {'pattern': r'(https?://\S{100,})', 'pattern_type': 'regex', 'is_active': True, 'hit_count': 0, 'description': 'Very long URLs'},
        {'pattern': r'(\S+)\1{10,}', 'pattern_type': 'regex', 'is_active': True, 'hit_count': 0, 'description': 'Repeated characters'},
        {'pattern': r'[A-Z]{20,}', 'pattern_type': 'regex', 'is_active': True, 'hit_count': 0, 'description': 'All caps text'},
        {'pattern': r'\b(viagra|cialis|lottery|winner|prize)\b', 'pattern_type': 'regex', 'is_active': True, 'hit_count': 0, 'description': 'Spam keywords'},
    ])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_scheduled_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_completed'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_celery_task_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_rate_limits_window_start'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_phone_number_window'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_game_states_user_id_game_type'), table_name='game_states')
    op.drop_index(op.f('ix_game_states_is_active'), table_name='game_states')
    op.drop_table('game_states')
    op.drop_index(op.f('ix_command_logs_user_id_created_at'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_created_at'), table_name='command_logs')
    op.drop_index(op.f('ix_command_logs_command'), table_name='command_logs')
    op.drop_table('command_logs')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('spam_patterns')
    op.drop_index(op.f('ix_command_aliases_alias'), table_name='command_aliases')
    op.drop_table('command_aliases')
    op.drop_index(op.f('ix_blocked_numbers_phone_number'), table_name='blocked_numbers')
    op.drop_table('blocked_numbers')
    # ### end Alembic commands ###
